### PR TITLE
Handle npm3 node_modules layouts

### PR DESCRIPTION
**Pull request by andrewimm**
With these changes, I can build MyProject on npm@3, and with a manually-build directory structure that resembles the one produced by npm@2.

It replaces the recursive package resource step with a two-pass process. The first remains nearly unchanged, but it defers package config validation until the second step. The second step then visits each package and iterates over its package.json dependencies. If a dependency was not found in a local node_modules directory, but it was seen elsewhere in the tree, the association is made anyways. This covers the npm3 case where most modules live at the top level, or in some higher nested tier. The completed package is then validated.

### CODE REVIEW

**Comment by jordwalke** [comment]
Awesome! @chenglou does this look good?

**Comment by jordwalke** [comment]
Did you test on npm2?

**Comment by chenglou** [comment]
Tried on `ExampleProjects/MyProject` with npm3. Seems to work (didn't test merlin yet)!

**Comment by andrewimm** [comment]
Found an old laptop running npm2 and tested this successfully (I'm not a fan of polluting my workspace with things like `nvm` and `nave`).

@chenglou do you feel comfortable accepting this?

**Comment by jordwalke** [comment]
Thanks @andrewimm !

**Pull request merged**
